### ISSUE TITLE
casint.interpreter.ParserException

### ISSUE THREAD

**Issue by joselbr2099** [jm-/casint#3]
good job but i get the following error when i try to open a g1m file

    D:\casint>python run.py input/captures/MM1.G1M
    Processing G1M file: input/captures/MM1.G1M
    Traceback (most recent call last):
      File "run.py", line 83, in <module>
        sys.exit(main(sys.argv[1]))
      File "run.py", line 30, in main
        items = load_items_from_g1m_file(path)
      File "D:\casint\casint\loader.py", line 501, in load_items_from_g1m_file
        items = g1mfile.load()
      File "D:\casint\casint\loader.py", line 408, in load
       items[i] = self._read_item(fp)
      File "D:\casint\casint\loader.py", line 317, in _read_item
        return self._read_program(item_title, item_data)
      File "D:\casint\casint\loader.py", line 263, in _read_program
        tree = parser.parse()
      File "D:\casint\casint\interpreter.py", line 631, in parse
        self.error()
      File "D:\casint\casint\interpreter.py", line 123, in error
        raise ParserException(
      casint.interpreter.ParserException: Invalid syntax: tok=Token(b'PROMPT', b'?') filepath=input/captures/MM1.G1M pos=43 ln=1 col=44 chr=b'\x0e' msg=`

attach the file:
[MM1.zip](https://github.com/jm-/casint/files/5592650/MM1.zip)

**Comment by jm-** [comment]
@joselbr2099, I haven't worked on this project in a while. iirc I think the PROMPT operator hasn't been fully implemented. I will have a closer look when I get some free time
